data:
    samples: data/samples
    popmap: data/popmap.tsv
    genome: data/genome.fa

analyses:
    - distrib
    - signif
    - depth
    - freq

params:
    general:
        min-depth: 5
        groups:
            group1: males
            group2: females
    process:
        min-depth: 1

multi_runs_file: 'data/runs.tsv'
# multi_runs_file:

resources:
    process:
        threads: 10

default_settings_file: 'cfg/defaults.yaml'

benchmarks_dir: benchmarks
logs_dir: logs
results_dir: results
